on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        deps:
          - { python: '3.7', django: '~=2.2.0', drf: '~=3.10.0' }
          - { python: '3.7', django: '~=3.2.0', drf: '~=3.11.0' }
          - { python: '3.8', django: '~=3.2.0', drf: '~=3.12.0' }
          - { python: '3.10', django: '~=3.2.0', drf: '~=3.12.0' }
          - { python: '3.9', django: '~=4.0.0', drf: '~=3.13.0' }
          - { python: '3.10', django: '~=4.0.0', drf: '~=3.13.0' }
      fail-fast: false
    name: Python ${{ matrix.deps.python }} / Django ${{ matrix.deps.django }} / DRF ${{ matrix.deps.drf }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.deps.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.deps.python }}
      - name: Upgrade pip
        run: pip install -U pip
      - name: Install dependencies
        run: pip install "django${{ matrix.deps.django }}" "djangorestframework${{ matrix.deps.drf }}"
      - name: Run tests
        run: python runtests.py

  check-formatting:
    runs-on: ubuntu-latest
    name: Check code formatting
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter
        uses: lgeiger/black-action@master
        with:
          args: "drf_dynamic_fields tests runtests.py --check --diff"
