on:
  push:
    branches:
      - master
  pull_request:

name: CI

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - '3.7'
          - '3.8'
        deps:
          - { django: '<2', drf: '<3.8' }
          - { django: '<2', drf: '<3.9' }
          - { django: '<2.1', drf: '<3.9' }
          - { django: '<2.2', drf: '<3.9' }
    name: Python ${{ matrix.python }} / Django ${{ matrix.deps.django }} / DRF ${{ matrix.deps.drf }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: pip install "django${{ matrix.deps.django }}" "django-rest-framework${{ matrix.deps.drf }}"
      - name: Run tests
        run: python runtests.py

    #check-formatting:
    #  runs-on: ubuntu-latest
    #  name: Check code formatting
    #  steps:
    #    - uses: actions/checkout@v2
    #    - name: Black Code Formatter
    #      uses: lgeiger/black-action@master
    #      with:
    #        args: "drf_dynamic_fields --check --diff"
